services:
  app:
    container_name: whatsapp_web_api
    build: .
    restart: always
    ports:
      - "5000:5000"
      - "8000:8000"
    env_file:
      - .env.example
    volumes:
      - ./sessions:/usr/src/app/sessions
